### ISSUE TITLE
can i interest you in forking this awesome extension?

### ISSUE THREAD

**Issue by roiz-git** [raindrum/gnome-citeurl-search-provider#1]
hey,
it used to be a great extension for custom search, basically you may execute any python/bash script with the search string as arguments. as long as the results were in fixed json structure it would have shown in the shell, it was released for 3.36 anf got broken in 3.38.

I see you have some skill in code (and software architecture) and I was wondering if you wanted to take ownership? it such a great extension!
[https://github.com/mont5piques/gnome_shell_custom_api_search](url)

**Comment by raindrum** [comment]
I'm flattered that you'd ask, but to be honest I'm not very familiar with GNOME extensions; it's a wonder that I managed to get *this* one working.

That does look like a cool extension, though. I'll look into getting it working on GNOME 40, and if I manage to do that, I'll file a pull request, but no promises, and I probably can't take over maintaining it long-term in any case. Sorry to disappoint.

In the meantime, I'm closing the issue since it isn't related to this project.

**Comment by roiz-git** [comment]
thanks!
